name: Release
on:
  release:
    types:
      - published
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
      - name: Install solc
        run: |
          sudo apt update 
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install solc
      - name: Compile solidity contracts
        run: make compile-solidity
      - name: Run GoReleaser for wasp
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser for wasp-cli
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist -f ./tools/wasp-cli/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
